changelog:
  categories:
    - title: 🐛 Bug Fixes
      labels: [ bug ]
    - title: ✨ AI Updates
      labels: [ ai ]
    - title: ⚙️ Calibration Updates
      labels: [ calib ]
    - title: 💾 Bank Schema Updates
      labels: [ schema ]
    - title: 🔘 GEMC Updates
      labels: [ gemc ]
    - title: 🔘 RG-L Updates
      labels: [ rg-l ]
    - title: 🚀 Performance Updates
      labels: [ speed ]
    - title: ▶️ CI Updates
      labels: [ ci ]
    - title: ☕ Java Updates
      labels: [ java ]
    - title: 🔧 Maven Updates
      labels: [ maven ]
    - title: 📦 Dependency Updates
      labels: [ dependencies ]
    - title: ⚡ QCDDAT Updates
      labels: [ qcddat ]
    - title: 🔘 Other Changes
      labels: [ '*' ]
