image: codecr.jlab.org/hallb/clas12/container-forge/base:latest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      auto_cancel:
        on_new_commit: interruptible
    - if: $CI_COMMIT_BRANCH == "main"
      auto_cancel:
        on_new_commit: conservative
    - if: $CI_COMMIT_TAG
      auto_cancel:
        on_new_commit: conservative

default:
  interruptible: true

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./build-coatjava.sh --clara -T$JL_RUNNER_AVAIL_CPU --quiet --no-progress
    - tar -czf coatjava.tar.gz coatjava
    - tar -czf clara.tar.gz clara
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - coatjava.tar.gz
      - clara.tar.gz

depana:
  allow_failure: true
  stage: build
  script:
    - libexec/dependency-tree.sh
    - libexec/dependency-analysis.sh

download:
  stage: build
  script:
    - xrdcp xroot://sci-xrootd.jlab.org///osgpool/hallb/clas12/validation/clas_005038.evio.00000 ./
    - xrdcp xroot://sci-xrootd.jlab.org///osgpool/hallb/clas12/validation/raw/rg-l/clas_021559.evio.00001 ./
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - clas_005038.evio.00000
      - clas_021559.evio.00000

spotbugs:
  stage: test
  needs: [build]
  dependencies: [build]
  script:
    - >
      tar -xzf coatjava.tar.gz &&
      ./build-coatjava.sh -T$JL_RUNNER_AVAIL_CPU --spotbugs --quiet --no-progress

unit_tests:
  stage: test
  needs: [build]
  dependencies: [build]
  script:
    - >
      tar -xzf coatjava.tar.gz &&
      ./build-coatjava.sh -T$JL_RUNNER_AVAIL_CPU --unittests --quiet --no-progress &&
      ./validation/jacoco-aggregate.sh
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - publish

docs:
  stage: test
  needs: [build,unit_tests]
  dependencies: [build,unit_tests]
  script:
    - >
      tar -xzf coatjava.tar.gz &&
      python3 -m venv venv &&
      source venv/bin/activate &&
      python3 -m pip install -r docs/mkdocs/requirements.txt &&
      ./docs/mkdocs/generate.sh pages &&
      libexec/build-javadocs.sh &&
      ls -l && ls -l pages && ls -l publish &&
      mv target/reports/apidocs pages/javadoc &&
      cp -r publish pages/jacoco
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - pages

eb:
  stage: test
  needs: [build]
  dependencies: [build]
  script:
    - >
      tar -xzf coatjava.tar.gz &&
      cd validation/advanced-tests && 
      ./run-eb-tests.sh -100 ${ARG}
  parallel:
    matrix:
      - ARG: electronproton 
      - ARG: electronprotonC 
      - ARG: electrongamma 
      - ARG: electronneutronC
      - ARG: electronFTpion

clara:
  allow_failure: true
  stage: test
  needs: [build]
  dependencies: [build]
  script:
    - >
      tar -xzf clara.tar.gz &&
      ./clara/plugins/clas12/bin/run-clara -c ./clara
        -t $JL_RUNNER_AVAIL_CPU -y ./etc/services/rgl-clarode.yml
        -n 100 -o ./out clas_021*.hipo

profile:
  stage: test
  needs: [build]
  dependencies: [build]
  script:
    - >
      tar -xzf coatjava.tar.gz &&
      libexec/profile.sh

deploy:
  stage: deploy
  script:
    - echo DEPLOY!!!

release:
  stage: deploy
  script:
    - echo RELEASE!!!

