#!/usr/bin/env bash

# Abort on any non-zero exit codes:
set -e

function error() {
    echo -e "$usage\n\nERROR:  $@"
    exit 1
}

function get() {
    [ "$debug" -eq 0 ] && wopts="--no-verbose" || wopts=""
    [ "$#" -gt 1 ]     && topts="-C $2 -xz"   || topts="-xz"
    [ "$debug" -gt 0 ] && topts+="v"
    wget $wopts $1
    tar $topts -f $(basename $1)
}

function litter() {
    if [ -d "$tmp_dir" ]
    then
        if [ "$1" -ne 0 ] || [ "$debug" -gt 1 ]
        then
            echo -e "\nSee build directory for more info:\n\t$tmp_dir"
        else
            rm -r $tmp_dir
            echo -e "\nRemoved temporary build directory:\n\t$tmp_dir"
        fi
    fi
}

function cleanup() {
    exit_code=$?
    if [ "$exit_code" -eq 0 ]
    then
        chmod a+x clara-cre/bin/*
        chmod -R a+r clara-cre
        mv clara-cre $clara_home
    fi
    litter $exit_code
    if [ "$exit_code" -eq 0 ]
    then
        if compgen -G "$clara_home/lib/jclara-*.jar" > /dev/null
        then
            echo -e "\n\$CLARA_HOME installed at $clara_home"
        fi
    fi
}

trap cleanup EXIT

# Configure:
grapes=2.17
clara=5.0.2
coatjava=9.0.1
debug=0
args=()
usage="Usage:  install-clara [-v] [-f CLARA] [-v COATJAVA] [-g GRAPES] [-j JRE] PATH"
info="\
- The default COATJAVA/CLARA/GRAPES versions are $coatjava/$clara/$grapes.\n\
- COATJAVA can also be specified as a local coatjava installation.\n\
- No JRE will be installed without the -j option.\n\
- The -v option (repeatable) increases verbosity and can disable cleanup.\n"
while [[ $# -gt 0 ]]
do
    case $1 in
        -h) echo $usage && echo -e "\n$info" && exit 0 ;;
        -f) clara="$2" && shift && shift ;;
        -c) coatjava="$2" && shift && shift ;;
        -g) grapes="$2" && shift && shift ;;
        -j) jre="$2" && shift && shift ;;
        -v) let debug=$debug+1 && shift ;;
        -*|--*)  echo -e "$usage\n\nUnknown option:  $1" && exit 1 ;;
        *) args+=("$1") && shift ;;
    esac
done

# Check requested installation path:
clara_home="$args"
[ "${#args[@]}" -lt 1 ] && error "Missing PATH argument"
[ "${#args[@]}" -gt 1 ] && error "Extra PATH arguments:  ${args[@]:1}"
[ -e "$clara_home" ]    && error "Installation PATH already exists:  $clara_home"
mkdir -p $clara_home    || error "Cannot create installation PATH:  $clara_home"
clara_home=$(cd $clara_home && pwd)
rmdir $clara_home

# Do everything inside a new, temporary directory:
[ -w "." ] || error "Current working directory is not writeable:  \$PWD=$PWD"
tmp_dir=$(mktemp -d install-clara.tmp.XXXXXX)
[ $? -ne 0 ] && error "Cannot create temporary directory:  $tmp_dir"
tmp_dir=$(cd $tmp_dir && pwd)
echo -e "\nCreating temporary build directory:\n\t$tmp_dir"
cd $tmp_dir

# CLARA:
echo -e "\nRetrieving CLARA version $clara ..."
get https://userweb.jlab.org/~gurjyan/clara-cre/clara-cre-$clara.tar.gz

# COATJAVA:
if compgen -G "$coatjava/lib/clas/coat-libs-*.jar" > /dev/null
then
    echo -e "\nUsing local COATJAVA installation:  $coatjava"
else
    echo -e "\nRetrieving COATJAVA version $coatjava ..."
    get https://clasweb.jlab.org/clas12offline/distribution/coatjava/coatjava-$coatjava.tar.gz
    coatjava=./coatjava
fi
mkdir -p clara-cre/plugins/clas12/lib/clas
mkdir -p clara-cre/plugins/clas12/lib/services
mkdir -p clara-cre/plugins/clas12/config
cp -r $coatjava/etc clara-cre/plugins/clas12/.
cp -r $coatjava/bin clara-cre/plugins/clas12/.
cp -r $coatjava/lib/utils clara-cre/plugins/clas12/lib/.
cp -r $coatjava/lib/clas/* clara-cre/plugins/clas12/lib/clas/.
cp -r $coatjava/lib/services/* clara-cre/plugins/clas12/lib/services/.

# GRAPES:
echo -e "\nRetrieving GRAPES version $grapes ..."
get https://clasweb.jlab.org/clas12offline/distribution/grapes/grapes-$grapes.tar.gz
mv grapes-$grapes clara-cre/plugins/grapes
cp -r clara-cre/plugins/grapes/bin/clara-grapes clara-cre/bin/

# JRE:
if ! [ -z ${jre+x} ]
then
    echo -e "\nRetrieving JRE version $jre ..."
    mkdir clara-cre/jre
    get https://userweb.jlab.org/~gurjyan/clara-cre/linux-64-$jre.tar.gz clara-cre/jre
fi

