<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.jlab.clas</groupId>
  <artifactId>coatjava</artifactId>
  <version>13.7.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <coat.deployment.url>file://myLocalMvnRepo</coat.deployment.url> <!-- must be consistent with 'deploy-coatjava.sh' -->
  </properties>

  <modules>
    <module>common-tools</module>
    <module>reconstruction</module>
  </modules>

  <repositories>
    <repository>
      <id>clas12maven</id>
      <url>https://clasweb.jlab.org/.clas12maven</url>
    </repository>
    <repository>
      <id>jnp-maven</id>
      <url>https://clasweb.jlab.org/.jhep/maven</url>
    </repository>
  </repositories>

  <profiles>
    <profile> <!-- skip unit tests by default -->
      <id>skip-tests</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <skipTests>true</skipTests>
      </properties>
    </profile>
  </profiles>

  <!-- :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

  <dependencyManagement>
    <dependencies>

      <dependency>
        <groupId>com.github.spotbugs</groupId>
        <artifactId>spotbugs</artifactId>
        <version>4.9.8</version>
      </dependency>

      <dependency>
        <groupId>jakarta.annotation</groupId>
        <artifactId>jakarta.annotation-api</artifactId>
        <version>3.0.0</version>
      </dependency>

      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.13.2</version>
        <scope>test</scope>
      </dependency>

      <dependency>
        <groupId>org.json</groupId>
        <artifactId>json</artifactId>
        <version>20251224</version>
      </dependency>

      <dependency>
        <groupId>org.yaml</groupId>
        <artifactId>snakeyaml</artifactId>
        <version>2.6</version>
      </dependency>

      <dependency>
        <groupId>org.openjfx</groupId>
        <artifactId>javafx-base</artifactId>
        <version>23.0.2</version>
        <classifier>linux</classifier>
      </dependency>

      <dependency>
        <groupId>org.openjfx</groupId>
        <artifactId>javafx-graphics</artifactId>
        <version>23.0.2</version>
        <classifier>linux</classifier>
      </dependency>

      <dependency>
        <groupId>org.openjfx</groupId>
        <artifactId>javafx-fxml</artifactId>
        <version>23.0.2</version>
        <classifier>linux</classifier>
      </dependency>

      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>2.0.17</version>
      </dependency>

      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-math3</artifactId>
        <version>3.6.1</version>
      </dependency>

      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-lang3</artifactId>
        <version>3.20.0</version>
      </dependency>

      <dependency>
        <groupId>org.jlab</groupId>
        <artifactId>groot</artifactId>
        <version>4.0.5</version>
      </dependency>

      <dependency>
        <groupId>org.freehep</groupId>
        <artifactId>jminuit</artifactId>
        <version>1.0</version>
      </dependency>

      <dependency>
        <groupId>org.jlab.coda</groupId>
        <artifactId>jclara</artifactId>
        <version>4.3</version>
      </dependency>

      <dependency>
        <groupId>org.jlab.coda</groupId>
        <artifactId>jevio</artifactId>
        <classifier>jar-with-dependencies</classifier>
        <version>6.2-SNAPSHOT</version>
        <exclusions>
          <exclusion>
            <groupId>net.jpountz.lz4</groupId>
            <artifactId>lz4-java</artifactId>
          </exclusion>
          <exclusion>
            <groupId>com.aha.compression</groupId>
            <artifactId> AHACompressionAPI </artifactId>
          </exclusion>
          <exclusion>
            <groupId>com.lmax</groupId>
            <artifactId>disruptor</artifactId>
          </exclusion>
          <exclusion>
            <groupId>proguard</groupId>
            <artifactId>proguard</artifactId>
          </exclusion>
        </exclusions>
      </dependency>

      <dependency>
        <groupId>org.jlab.jnp</groupId>
        <artifactId>jnp-hipo</artifactId>
        <version>2.0-SNAPSHOT</version> <!-- WARNING: if changed, check the `net.objecthunter:exp4j` version; see `docs/dependency_conflicts.md` -->
      </dependency>

      <dependency>
        <groupId>org.jlab.jnp</groupId>
        <artifactId>jnp-hipo4</artifactId>
        <version>4.3-SNAPSHOT</version> <!-- WARNING: if changed, check the `net.objecthunter:exp4j` version; see `docs/dependency_conflicts.md` -->
      </dependency>

      <dependency>
        <groupId>j4ml</groupId>
        <artifactId>j4ml-neuroph</artifactId>
        <version>0.9-SNAPSHOT</version>
      </dependency>

      <dependency>
        <groupId>j4ml</groupId>
        <artifactId>j4ml-data</artifactId>
        <version>0.9-SNAPSHOT</version>
      </dependency>

      <dependency>
        <groupId>j4ml</groupId>
        <artifactId>j4ml-clas12</artifactId>
        <version>0.9-SNAPSHOT</version> <!-- WARNING: if changed, check the `org.ejml:ejml-simple` version; see `docs/dependency_conflicts.md` -->
      </dependency>

      <dependency>
        <groupId>org.jlab.ccdbrcdb</groupId>
        <artifactId>ccdbrcdb</artifactId>
        <version>2.0</version>
      </dependency>

      <dependency>
        <groupId>gov.nist.math</groupId>
        <artifactId>jama</artifactId>
        <version>1.0.3</version>
      </dependency>

      <dependency> <!-- sets version number for all 'ai.djl' dependencies -->
        <groupId>ai.djl</groupId>
        <artifactId>bom</artifactId>
        <version>0.36.0</version> <!-- WARNING: if changed, check the `com.google.code.gson:gson` version; see `docs/dependency_conflicts.md` -->
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <!-- BEGIN DEPENDENCY CONFLICT RESOLUTION -->
      <!--
        the following dependency versions are specified to resolve dependency tree conflicts
        - see also exclusions in `maven-enforcer-plugin`
        - see `docs/dependency_conflicts.md` for more info
      -->

      <!-- resolve conflict between `org.jlab.jnp:jnp-hipo:jar:2.0-SNAPSHOT` and `org.jlab.jnp:jnp-hipo4:jar:4.3-SNAPSHOT`
           by choosing the later version of their `net.objecthunter:exp4j` dependency -->
      <dependency>
        <groupId>net.objecthunter</groupId>
        <artifactId>exp4j</artifactId>
        <version>0.4.8</version> <!-- WARNING: if changed, see `docs/dependency_conflicts.md` -->
      </dependency>

      <!-- resolve conflict between `org.jlab.coda:jclara` and `ai.djl:api`
           by choosing the later version of their `com.google.code.gson:gson` dependency
           - `djl`'s `gson` version is here: https://github.com/deepjavalibrary/djl/blob/master/gradle/libs.versions.toml
      -->
      <dependency>
        <groupId>com.google.code.gson</groupId>
        <artifactId>gson</artifactId>
        <version>2.13.1</version> <!-- WARNING: if changed, see `docs/dependency_conflicts.md` -->
      </dependency>

      <!-- resolve conflict between `j4ml:j4ml-clas12` and `clas-tracking`
           by using the version of `org.ejml:ejml-simple` used by `j4ml:j4ml-clas12:jar:0.9-SNAPSHOT` -->
      <dependency>
        <groupId>org.ejml</groupId>
        <artifactId>ejml-simple</artifactId>
        <version>0.40</version> <!-- WARNING: if changed, see `docs/dependency_conflicts.md` -->
      </dependency>

      <!-- END DEPENDENCY CONFLICT RESOLUTION -->

    </dependencies>
  </dependencyManagement>

  <!-- :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

  <build>

    <extensions>
      <extension>
        <groupId>org.apache.maven.wagon</groupId>
        <artifactId>wagon-ssh-external</artifactId>
        <version>3.5.3</version>
      </extension>
    </extensions>

    <!-- .................................................................................. -->

    <plugins> <!-- plugins inherited by all child POMs -->

      <!-- static analysis -->
      <plugin>
        <groupId>com.github.spotbugs</groupId>
        <artifactId>spotbugs-maven-plugin</artifactId>
        <version>4.9.8.2</version>
        <configuration>
          <excludeFilterFile>spotbugs-exclude.xml</excludeFilterFile>
        </configuration>
      </plugin>

      <!-- documentation generation -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.12.0</version>
        <configuration>
          <doctitle>COATJAVA - API documentation - version ${project.version}</doctitle>
          <windowtitle>COATJAVA - API documentation - version ${project.version}</windowtitle>
          <encoding>UTF-8</encoding>
          <doclint>none</doclint>
        </configuration>
        <executions>
          <execution>
            <id>aggregate</id>
            <goals>
              <goal>aggregate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- general settings -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.15.0</version>
        <configuration>
          <release>21</release> <!-- CI variable `JAVA_VERSION` must match this; see also dependabot configuration -->
          <encoding>UTF-8</encoding>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.5.0</version>
        <configuration>
          <encoding>UTF-8</encoding>
        </configuration>
      </plugin>

      <!-- JAR -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.5.0</version>
        <configuration>
          <archive>
            <manifest>
              <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
              <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
            </manifest>
            <manifestSections>
              <manifestSection>
                <name>${project.name}</name>
                <manifestEntries>
                  <groupId>${project.groupId}</groupId>
                  <artifactId>${project.artifactId}</artifactId>
                  <version>${project.version}</version>
                </manifestEntries>
              </manifestSection>
            </manifestSections>
          </archive>
        </configuration>
      </plugin>

      <!-- dependency analysis -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.10.0</version>
        <executions>
          <execution>
            <id>analyze</id>
            <phase>verify</phase>
            <goals>
              <goal>tree</goal>
              <goal>analyze-only</goal>
            </goals>
            <configuration>
              <failOnWarning>true</failOnWarning>
              <!-- ignore certain "unused but declared" warnings -->
              <ignoredUnusedDeclaredDependencies>
                <ignoredUnusedDeclaredDependency>ai.djl:model-zoo</ignoredUnusedDeclaredDependency>
                <ignoredUnusedDeclaredDependency>ai.djl.pytorch:pytorch-model-zoo</ignoredUnusedDeclaredDependency>
                <ignoredUnusedDeclaredDependency>ai.djl.pytorch:pytorch-engine</ignoredUnusedDeclaredDependency>
                <ignoredUnusedDeclaredDependency>ai.djl.pytorch:pytorch-native-cpu</ignoredUnusedDeclaredDependency>
                <ignoredUnusedDeclaredDependency>ai.djl.pytorch:pytorch-jni</ignoredUnusedDeclaredDependency>
              </ignoredUnusedDeclaredDependencies>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- enforcers -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>3.6.2</version>
        <executions>
          <!-- dependency convergence -->
          <execution>
            <id>enforce-dependency-convergence</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <dependencyConvergence>
                  <excludes>
                    <!-- excluding conflicts that may be tricky to resolve -->
                    <exclude>com.google.protobuf:protobuf-java</exclude> <!-- `org.jlab.ccdbrcdb:ccdbrcdb` use v3, but `org.jlab.coda.xmsg` uses v2 -->
                  </excludes>
                </dependencyConvergence>
              </rules>
            </configuration>
          </execution>
          <!-- Java version enforcer -->
          <execution>
            <id>enforce-java</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireJavaVersion>
                  <version>[21,)</version>
                </requireJavaVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- coverage -->
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.14</version>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

    </plugins>

    <!-- .................................................................................. -->

    <pluginManagement>
      <plugins> <!-- plugin configurations (unused in child POMs unless declared) -->

        <!-- generate minimal POM files for deployment, containing GAV (groupID, artifactId, version) -->
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>flatten-maven-plugin</artifactId>
          <version>1.7.3</version>
          <configuration>
            <flattenMode>fatjar</flattenMode>
          </configuration>
          <executions>
            <execution>
              <id>flatten</id>
              <phase>package</phase>
              <goals>
                <goal>flatten</goal>
              </goals>
            </execution>
          </executions>
        </plugin>

        <!-- deployment configuration -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>3.1.4</version>
          <configuration>
            <!-- Use the minimal GAV POM -->
            <pomFile>${project.build.directory}/.flattened-pom.xml</pomFile>
          </configuration>
        </plugin>

      </plugins>
    </pluginManagement>

  </build>

</project>
