#!/bin/bash

#ulimit -u 49152
set -e

inputdir=.
outputdir=.
threads=2
usage="Usage:  run-clara -y yamlfile [-i dir] [-o dir] [-t threads] [-n nevents] [CLARA_HOME]"

while [[ $# -gt 0 ]]; do
    case $1 in
        -h) echo -e "$usage" && exit 0 ;;
        -i) inputdir="$2" && shift && shift ;;
        -o) outputdir="$2" && shift && shift ;;
        -t) threads="$2" && shift && shift ;;
        -n) nevents="$2" && shift && shift ;;
        -y) yaml="$2" && shift && shift ;;
        -*|--*)  echo -e "$usage\n\nUnknown option:  $1" && exit 1 ;;
        *) args+=("$1") && shift ;;
    esac
done

function error() {
    echo -e "\n$usage\n\nERROR:  $@"
    exit 1
}

if [ "${#args[@]}" -lt 1 ]; then
    [ -z ${CLARA_HOME+x} ] && error "CLARA_HOME undefined."
else
    [ "${#args[@]}" -gt 1 ] && error "Extra arguments:  ${args[@]:1}"
    export CLARA_HOME="$args"
fi
[ ! -e "$CLARA_HOME" ]  && error "Missing CLARA_HOME:  $CLARA_HOME"
[ -z ${yaml+x} ] && error "-y YAML must be specified."
[ -r $yaml ] || error "YAML file does not exist."
[ -d $inputdir ] || error "Input dir does not exist."

[ $threads -eq 0 ] && threads=`grep -c ^processor /proc/cpuinfo`

unset CLARA_MONITOR_FE
export CLARA_USER_DATA=$(mktemp -d $outputdir/run-clara.tmp.XXXXXX)
cd $CLARA_USER_DATA
mkdir -p $CLARA_USER_DATA/log
mkdir -p $CLARA_USER_DATA/config
mkdir -p $CLARA_USER_DATA/data/output

find $inputdir -maxdepth 1 -type f -name '*.hipo' | sed 's;^\./;;' | sort > filelist.txt
[ $(stat -L -c%s filelist.txt) -gt 0 ] || error "Found no input files"

$CLARA_HOME/lib/clara/run-clara \
        -i $inputdir \
        -o $CLARA_USER_DATA \
        -z rec_ \
        -x $CLARA_USER_DATA/log \
        -t $threads \
        $nevents \
        -s recon \
        $yaml \
        ./filelist.txt

