# set the global logger config; `SplitLogger` will override these settings
handlers = java.util.logging.ConsoleHandler
java.util.logging.SimpleFormatter.format = %5$s%6$s%n
java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

# set the log level for each class
org.jlab.logging.TestSplitLogger.level = FINEST
