### the finest possible logging level
org.jlab.logging.TestSplitLogger.level = FINEST

### or less fine levels
# org.jlab.logging.TestSplitLogger.level = FINER
# org.jlab.logging.TestSplitLogger.level = FINE
