### the finest possible logging level
org.jlab.logging.TestLogManager.level = FINEST

### or less fine levels
# org.jlab.logging.TestLogManager.level = FINER
# org.jlab.logging.TestLogManager.level = FINE
