<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.jlab.clas12.detector</groupId>
  <artifactId>clas12detector-alert</artifactId>
  <version>13.8.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <parent>
    <groupId>org.jlab.clas12</groupId>
    <artifactId>reconstruction</artifactId>
    <version>13.8.1-SNAPSHOT</version>
  </parent>

  <dependencies>
    <dependency>
      <groupId>gov.nist.math</groupId>
      <artifactId>jama</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-math3</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jlab.clas</groupId>
      <artifactId>clas-reco</artifactId>
      <version>13.8.1-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.jlab.clas</groupId>
      <artifactId>clas-io</artifactId>
      <version>13.8.1-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jlab.clas</groupId>
      <artifactId>clas-analysis</artifactId>
      <version>13.8.1-SNAPSHOT</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jlab.clas</groupId>
      <artifactId>clas-tracking</artifactId>
      <version>13.8.1-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jlab.clas</groupId>
      <artifactId>clas-geometry</artifactId>
      <version>13.8.1-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jlab.clas</groupId>
      <artifactId>clas-utils</artifactId>
      <version>13.8.1-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jlab.clas</groupId>
      <artifactId>clas-detector</artifactId>
      <version>13.8.1-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jlab.clas</groupId>
      <artifactId>clas-physics</artifactId>
      <version>13.8.1-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jlab.clas</groupId>
      <artifactId>swim-tools</artifactId>
      <version>13.8.1-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
    </dependency>
    <dependency>
      <groupId>ai.djl</groupId>
      <artifactId>api</artifactId>
    </dependency>

    <!-- 'ai.djl' runtime dependencies -->
    <!-- DJL Model Zoo -->
    <dependency>
      <groupId>ai.djl</groupId>
      <artifactId>model-zoo</artifactId>
      <scope>runtime</scope>
    </dependency>
    <!-- PyTorch Model Zoo -->
    <dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-model-zoo</artifactId>
      <scope>runtime</scope>
    </dependency>
    <!-- PyTorch Engine -->
    <dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-engine</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-native-cpu</artifactId>
      <classifier>linux-x86_64</classifier>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-jni</artifactId>
      <scope>runtime</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <!-- install 'ai.djl' runtime dependencies -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.10.0</version>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/lib/services</outputDirectory>
              <includeGroupIds>ai.djl</includeGroupIds>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
