package org.jlab.io.banks;
public class CVT__Seeds {
    public static final short ID = 0;
    public static final short fittingMethod = 1;
    public static final short q = 2;
    public static final short p = 3;
    public static final short pt = 4;
    public static final short phi0 = 5;
    public static final short tandip = 6;
    public static final short z0 = 7;
    public static final short d0 = 8;
    public static final short cov_d02 = 9;
    public static final short cov_d0phi0 = 10;
    public static final short cov_d0rho = 11;
    public static final short cov_phi02 = 12;
    public static final short cov_phi0rho = 13;
    public static final short cov_rho2 = 14;
    public static final short cov_z02 = 15;
    public static final short cov_z0tandip = 16;
    public static final short cov_tandip2 = 17;
    public static final short circlefit_chi2_per_ndf = 18;
    public static final short linefit_chi2_per_ndf = 19;
    public static final short chi2 = 20;
    public static final short ndf = 21;
    public static final short Cross1_ID = 22;
    public static final short Cross2_ID = 23;
    public static final short Cross3_ID = 24;
    public static final short Cross4_ID = 25;
    public static final short Cross5_ID = 26;
    public static final short Cross6_ID = 27;
    public static final short Cross7_ID = 28;
    public static final short Cross8_ID = 29;
    public static final short Cross9_ID = 30;
    public static final short xb = 31;
    public static final short yb = 32;
    public static final short fracmctru = 33;
    public static final short fracmcmatch = 34;
}
