package org.jlab.asdf;
public class HitBasedTrkg__AISegments {
    public static final short id = 0;
    public static final short status = 1;
    public static final short sector = 2;
    public static final short superlayer = 3;
    public static final short Cluster_ID = 4;
    public static final short Hit1_ID = 5;
    public static final short Hit2_ID = 6;
    public static final short Hit3_ID = 7;
    public static final short Hit4_ID = 8;
    public static final short Hit5_ID = 9;
    public static final short Hit6_ID = 10;
    public static final short Hit7_ID = 11;
    public static final short Hit8_ID = 12;
    public static final short Hit9_ID = 13;
    public static final short Hit10_ID = 14;
    public static final short Hit11_ID = 15;
    public static final short Hit12_ID = 16;
    public static final short avgWire = 17;
    public static final short fitChisqProb = 18;
    public static final short fitSlope = 19;
    public static final short fitSlopeErr = 20;
    public static final short fitInterc = 21;
    public static final short fitIntercErr = 22;
    public static final short SegEndPoint1X = 23;
    public static final short SegEndPoint1Z = 24;
    public static final short SegEndPoint2X = 25;
    public static final short SegEndPoint2Z = 26;
    public static final short size = 27;
}
