package org.jlab.asdf;
public class MC__True {
    public static final short detector = 0;
    public static final short pid = 1;
    public static final short mpid = 2;
    public static final short tid = 3;
    public static final short mtid = 4;
    public static final short otid = 5;
    public static final short trackE = 6;
    public static final short totEdep = 7;
    public static final short avgX = 8;
    public static final short avgY = 9;
    public static final short avgZ = 10;
    public static final short avgLx = 11;
    public static final short avgLy = 12;
    public static final short avgLz = 13;
    public static final short px = 14;
    public static final short py = 15;
    public static final short pz = 16;
    public static final short vx = 17;
    public static final short vy = 18;
    public static final short vz = 19;
    public static final short mvx = 20;
    public static final short mvy = 21;
    public static final short mvz = 22;
    public static final short avgT = 23;
    public static final short nsteps = 24;
    public static final short procID = 25;
    public static final short hitn = 26;
}
