package org.jlab.io.banks;
public class REC__Calorimeter {
    public static final short index = 0;
    public static final short pindex = 1;
    public static final short detector = 2;
    public static final short sector = 3;
    public static final short layer = 4;
    public static final short energy = 5;
    public static final short time = 6;
    public static final short path = 7;
    public static final short chi2 = 8;
    public static final short x = 9;
    public static final short y = 10;
    public static final short z = 11;
    public static final short hx = 12;
    public static final short hy = 13;
    public static final short hz = 14;
    public static final short lu = 15;
    public static final short lv = 16;
    public static final short lw = 17;
    public static final short du = 18;
    public static final short dv = 19;
    public static final short dw = 20;
    public static final short m2u = 21;
    public static final short m2v = 22;
    public static final short m2w = 23;
    public static final short m3u = 24;
    public static final short m3v = 25;
    public static final short m3w = 26;
    public static final short status = 27;
}
