#!/usr/bin/env python3
import glob,json
idir = 'etc/bankdefs/hipo4'
odir = 'common-tools/clas-io/src/main/java/org/jlab/io/banks'
for x in glob.glob(f'{idir}/*.json'):
    for bank in json.load(open(x,'r')):
        class_name = bank['name'].replace(':','_');
        with open(f'{odir}/{class_name}.java','w') as f:
            f.write('package org.jlab.asdf;\n')
            f.write(f'public class {class_name} {{\n')
            for i,entry in enumerate(bank['entries']):
                var_name = entry['name']
                f.write(f'    public static final short {var_name} = {i};\n')
            f.write('}\n')
            f.close()
