#!/bin/bash

a=development
b=redecodering2

for x in $a/*.hipo
do
    y=$b/$(basename $x)
    stub=$(basename $x)
    stub=${stub%%.*}
    hipo-diff -q 1 -s 0,1,2 -n 10000 $x $y >& $stub.log &
done

wait
