#!/bin/bash

event=cpu
format=flat
seconds=12
usage="Usage:  profile [-h] [-s seconds] [-w seconds] [-e event] [-f format] [--] executable args"
usage2="Usage:  profile [options] executable args\nOptions:\n\t[-h] [-s seconds] [-w seconds]\n\t[-e cpu|alloc|nativemem|lock|cache-misses]\n\t[-f flat|traces|collapsed|flamegraph|tree|jfr|otlp]"

while getopts s:f:e:o:w:h opt
do
    case $opt in
        s) seconds=$OPTARG ;;
        f) format=$OPTARG ;;
        e) event=$OPTARG ;;
        o) stub=$OPTARG ;;
        w) warmup=$OPTARG ;;
        h) echo -e $usage2 && exit 0 ;;
        --) break ;;
        \?) echo $usage && exit 1 ;;
#        :) echo $usage && exit 2 ;;
    esac
done

shift $((OPTIND-1))
executable=$1
arguments=${@:2}

which asprof >& /dev/null
[ "$?" -ne 0 ] && echo 'ERROR:  asprof is not in $PATH.' && exit 3

which $executable >& /dev/null
[ "$?" -ne 0 ] && echo "ERROR:  $executable is not in \$PATH." && exit 4

echo "Running asprof on '$executable $arguments' ..."

set -e

$executable $arguments >& asprof_$stub.log

pid_bash=$!

echo PID1=$pid_bash
sleep 5
pid_java=$(pgrep -P "$pid_bash")

echo PID2=$pid_java

ps waux && ps -p $pid_java

echo "Waiting for $warmup seconds of warmup ..."
for x in $(seq $warmup); do let y=$warmup-$x && echo -e -n "\r$y ..." && sleep 1; done

# This 42 is probably for recon-util:
tail -n 42 asprof_$stub.log

asprof --title "Coatjava:asprof:$executable:$event"  -e $event \
    -d $seconds -o $format -f asprof_${format}_${event}_$stub $pid_java

kill -9 $pid_java
rm -f asprof_$stub.hipo

