#!/bin/bash

# configure:
event=cpu #nativemem
format=flat
nevents=1000
seconds=12
yaml=etc/services/data-ai-uber.yml
while getopts y:n:f:e:s:h opt
do
    case $opt in
        s) seconds=$OPTARG ;;
        y) yaml=$OPTARG ;;
        n) nevents=$OPTARG ;;
        f) format=$OPTARG ;;
        e) event=$OPTARG ;;
        h) echo "\nUsage:  profile [-y YAML] [-n #] [-e EVENT] datafile" && exit 0 ;;
    esac
done
shift $((OPTIND-1))
data=$1
stub=$(basename $data)

which asprof >& /dev/null
[ "$?" -ne 0 ] && echo 'ERROR:  asprof is not in $PATH.' && exit 9

recon-util -y $yaml -n $nevents -o pro_$stub.hipo -i $data >& pro_$stub.log &
pid_bash=$!

echo PID1=$pid_bash
sleep 5
pid_java=$(pgrep -P "$pid_bash")

echo PID2=$pid_java

ps waux && ps -p $pid

echo "Waiting for 60 seconds of CoatJava warmup ..."
for x in $(seq 60); do let y=60-$x && echo -e -n "\r$y ..." && sleep 1; done

cat pro_$stub.log

asprof -e $event -d $seconds -o $format -f pro_${format}_${event}_$stub.html $pid_java

kill -9 $pid_java

