#!/bin/bash

exe=decoder4u -n 10000
csv=gold.csv
cache=$(cd $(dirname ${BASH_SOURCE[0]}) &> /dev/null && pwd)/pin-gold.txt
IFS=$'\n'

for x in $(tail -n +2 $csv)
do
    x=${x//[[:space:]]/}
    run=${x##*,}
    period=${x%%,*}
    stub=${period}_${run}
    data=$(grep ${run} $cache | grep 1$)
    $exe -o $stub.hipo $data >& $stub.log &
done

wait

