<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.jlab.clas</groupId>
    <artifactId>validation</artifactId>
    <version>13.0.2-SNAPSHOT</version>
    <packaging>pom</packaging>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <executable>./run-eb-tests.sh</executable>
                    <workingDirectory>advanced-tests</workingDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>ep</id>
                        <goals><goal>exec</goal></goals>
                        <configuration>
                            <arguments>
                                <argument>electronproton</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>epC</id>
                        <phase>test</phase>
                        <goals><goal>exec</goal></goals>
                        <configuration>
                            <arguments>
                                <argument>electronprotonC</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>egFT</id>
                        <phase>test</phase>
                        <goals><goal>exec</goal></goals>
                        <configuration>
                            <arguments>
                                <argument>electrongammaFT</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>egFT</id>
                        <phase>test</phase>
                        <goals><goal>exec</goal></goals>
                        <configuration>
                            <arguments>
                                <argument>electrongammaFT</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>egFTpi</id>
                        <phase>test</phase>
                        <goals><goal>exec</goal></goals>
                        <configuration>
                            <arguments>
                                <argument>electronFTpion</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build> 
</project>
