# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Coatjava-CI

on:
  pull_request:
  push:
    branches: [ development ]
    tags: [ '*' ]
  schedule:
    # NOTE: From what I read, the email notification for cron can only go
    #       to the last committer of this file!!!!!
    - cron: '0 22 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  JAVA_VERSION: 21 # must be consistent with POM; see also dependabot config for any version limits
  JAVA_VERSION_LATEST: 25 # the latest `JAVA_VERSION` that we test with CI
  java_distribution: zulu
  javadoc_version: 25 # newer than `JAVA_VERSION` for better javadoc
  groovy_version: 4.x
  CCDB_CONNECTION: 'sqlite:////cvmfs/oasis.opensciencegrid.org/jlab/hallb/clas12/sw/noarch/data/ccdb/ccdb_latest.sqlite'
  nthreads: 1

jobs:

  test_lfs:
    runs-on: ubuntu-latest
    env:
      GIT_LFS_SKIP_SMUDGE: 1 # skip automatic LFS checkout
    steps:
      - run: git lfs install
      - name: git clone
        run: git clone --depth 1 https://code.jlab.org/hallb/clas12/validation-data.git
      - run: tree
        working-directory: validation-data
      - run: git status
        working-directory: validation-data
      - run: git lfs pull -I README.md
        working-directory: validation-data
      - name: pull evio
        working-directory: validation-data
        run: |
          for f in $(find raw -type f); do
            echo "PULL $f"
            git lfs pull -I $f || echo "FAILED TO PULL $f"
          done
      - name: pull tarballs
        working-directory: validation-data
        run: |
          for f in $(find recon -type f -name "*.zst"); do
            echo "PULL $f"
            git lfs pull -I $f || echo "FAILED TO PULL $f"
          done
